@startuml

actor "User" as user
actor "Admin" as admin

node "batik-pedia-restful-api" {
 component "Controller" as controller
}

node "batik-pedia-dashboard"{
    component "AdminController" as admin_controller
}

database "PostgreSQL" as database

user <--> controller
controller <--> database

admin <--> admin_controller
admin_controller <--> database

@enduml
